colorscheme solarized-dark

add-highlighter global/ number-lines -relative -hlcursor 
add-highlighter global/ wrap -word -indent -marker >>
face global LineNumberCursor header

# , should remove selections like in helix (and future kak?)
map global normal <space> ,
map global normal , <space>

# https://github.com/Delapouite/kakoune-cd/blob/master/cd.kak
# %sh{dirname "${kak_buffile}"}
# 
define-command -params ..1 sh %{
    terminal sh -c "cd $1; ${2:-$SHELL}" \
    _unused_ %sh{dirname $kak_buffile} %arg[1]
}
# define-command -params ..1 sh  terminal sh -c "cd $1; $SHELL" _unused_ %sh{dirname $kak_buffile}
# terminal vim %val{buffile}

