#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true   # Probably need to undo

[options]
    # Ilya stuff
    statusline_unicode_symbols = true
    autocomplete_parens = false
    vimcompatible = true   # Or just windows_leader = ""? 

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# Ilya stuff

[[layers]]  # Fuzzy search
# name = 'fzf'
name = 'leaderf'
# name = 'unite'

[[layers]]
name = 'git'

[[layers]]
name = 'debug'

# [[layers]]
# name = 'ui'

[[custom_plugins]]
repo = "dag/vim-fish"  # Probably still better to put this in the bundle place??
merged = false  # Unsure what this does
