# TODO: Move comments from alacritty.yml
[colors.bright]
black = "#5a524c"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#b85651"
white = "#ddc7a1"
yellow = "#d8a657"

[colors.cursor]
cursor = "#d4be98"

[colors.normal]
black = "#3c3836"
blue = "#68948a"
cyan = "#72966c"
green = "#8f9a52"
magenta = "#ab6c7d"
red = "#b85651"
white = "#a89984"
yellow = "#c18f41"

[colors.primary]
background = "#32302f"
foreground = "#d4be98"

[font]
size = 12.0

[font.normal]
family = "Fira Code"
style = "Medium"

[[hints.enabled]]
action = "Paste"
regex = "([k-z]{5,}|[K-Z]{5,}|[0-9a-fA-F]{5,})"

[hints.enabled.binding]
key = "H"
mods = "Control|Shift"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Shift|Control|Alt"

[window]
decorations_theme_variant = "Dark"
option_as_alt = "Both"
