theme="solarized_dark"
# theme="autumn"

[editor]
soft-wrap.enable=true
soft-wrap.max-indent-retain=20
auto-pairs=false

line-number="relative"
true-color=true
# gutters=["line-numbers"] # Not "diagnostics"

# [editor.lsp]
# display-messages=true

[keys.normal]
x="extend_to_line_bounds"
X="extend_line_below"

"C-/"="toggle_comments"
"C-A-r"=":config-reload"

[keys.normal."C-A-d"]
# s=":open ~/dev/helix/book/src/SUMMARY.md"  # Not very useful
k=":open ~/dev/helix/book/src/keymap.md"
# r=":open ~/dev/helix/book/src/remapping.md" # Not very useful
c=":open ~/dev/helix/book/src/generated/typable-cmd.md"
u=":open ~/dev/helix/book/src/usage.md"
