[user]
name =  "Ilya Grigoriev"
email = "ilyagr@users.noreply.github.com"

[ui]
diff-editor = "vimdirdiff"
merge-editor = "vimdiff"
# merge-editor = "meld"
# merge-editor = "kdiff3"
color = "always"
relative-timestamps = true
unique-prefixes = "underscore"

[merge-tools.kdiff3]
edit-args = ["--merge", "--cs", "CreateBakFiles=0", "--cs", "SkipDirStatus=1"]

[merge-tools.kd]
# Possibly useless, no --merge
edit-args = ["--cs", "CreateBakFiles=0", "--cs", "SkipDirStatus=1"]
# No auto
kdiff3.merge-args = ["$base", "$left", "$right", "-o", "$output"]
program="kdiff3"

[merge-tools.bcompare]
merge-args = ["$left", "$base", "$right", "$output"]
merge-tool-edits-conflict-markers=true

# meld.merge-args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]
# vimdiff.merge-args = ["-f", "-d", "$output", "-M",
#                       "$left", "$base", "$right",
#                       "-c", "wincmd J", "-c", "set modifiable",
#                       "-c", "set write"]

[alias]
# Will probably delete these
prev = ["co", "@--"]
next = ["co", "@-+ ~ @"]

[revset-aliases]
next = "@-+ ~ @"  # After `jj up abc`, `jj up next` is equivalent to `jj up abc+`
M = "present(main) | present(master)"  # Main branch
# R: "relevant commits" from jj.logstatus. Better name?
R ="M..@|(M..@)-|@..M|@|M..branches()|(M..branches())-|M|remote_branches().. | (remote_branches()..)-"

[template.log]
# 
# if(divergent, label("divergent", "??"))
# if(divergent, label("divergent", " divergent"))

# change_id.short()
# if(divergent, label("divergent", "??"))


[colors]
"divergent change_id"="red"
"working_copy divergent change_id"="bright red"
