[user]
name =  "Ilya Grigoriev"
email = "ilyagr@users.noreply.github.com"

[ui]
diff-editor = "vimdirdiff"
merge-editor = "vimdiff"
# merge-editor = "meld"
# merge-editor = "kdiff3"
color = "always"

# [merge-tools]
# meld.merge-args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]
# kdiff3.merge-args = ["$base", "$left", "$right", "-o", "$output", "--auto"]
# vimdiff.merge-args = ["-f", "-d", "$output", "-M",
#                       "$left", "$base", "$right",
#                       "-c", "wincmd J", "-c", "set modifiable",
#                       "-c", "set write"]
# vimdiff.merge-tool-edits-conflict-markers=true

[alias]
# Will probably delete these
prev = ["co", "@--"]
next = ["co", "@-+ ~ @"]

[revset-aliases]
next = "@-+ ~ @"  # After `jj up abc`, `jj up next` is equivalent to `jj up abc+`

[template.log]
# if(divergent, label("warning",change_id.short()) ,change_id.short())
# if(divergent, label("divergent", "??"))
# if(divergent, label("divergent", " divergent"))
graph='''
change_id.short()
if(divergent, label("divergent", "??"))
" " author.email()
" " label("timestamp", committer.timestamp())
if(branches, " " branches)
if(tags, " " tags)
if(working_copies, " " working_copies)
if(is_git_head, label("git_head", " HEAD@git"))
" " commit_id.short()
if(conflict, label("conflict", " conflict"))
"\n"
description.first_line()
"\n"
'''
