[user]
name =  "Ilya Grigoriev"
email = "ilyagr@users.noreply.github.com"

[ui]
diff-editor = "vimdirdiff"
merge-editor = "vimdiff"
# merge-editor = "meld"
# merge-editor = "kdiff3"
color = "always"
relative-timestamps = true
graph.format="curved"
unique-prefixes = "styled"

[merge-tools.diff]
edit-args = ["-r", "--brief", "--new-file"]
[merge-tools.git]
edit-args = ["diff", "--no-index", "--name-only"]

[merge-tools.kdiff3]
edit-args = ["--merge", "--cs", "CreateBakFiles=0", "--cs", "SkipDirStatus=1"]

[merge-tools.kdiff3f] # Flipped
merge-args = [ "$base",  "$right","$left", "-o", "$output", "--auto",]
program="kdiff3"

[merge-tools.kd]
# Possibly useless, no --merge
edit-args = ["--cs", "CreateBakFiles=0", "--cs", "SkipDirStatus=1"]
# No auto
merge-args = ["$base", "$left", "$right", "-o", "$output"]
program="kdiff3"


[merge-tools.bcompare]
merge-args = ["$left", "$base", "$right", "$output"]
merge-tool-edits-conflict-markers=true

# meld.merge-args = ["$left", "$base", "$right", "-o", "$output", "--auto-merge"]
# vimdiff.merge-args = ["-f", "-d", "$output", "-M",
#                       "$left", "$base", "$right",
#                       "-c", "wincmd J", "-c", "set modifiable",
#                       "-c", "set write"]

[alias]
# Will probably delete these
prev = ["co", "@--"]
next = ["co", "@-+ ~ @"]

[revset-aliases]
next = "@-+ ~ @"  # After `jj up abc`, `jj up next` is equivalent to `jj up abc+`
M = "present(main) | present(master)"  # Main branch
# R: "relevant commits" from jj.logstatus. Better name?
R ="M..@|(M..@)-|@..M|@|M..branches()|(M..branches())-|M|remote_branches().. | (remote_branches()..)-"

[template.log]
# 
# if(divergent, label("divergent", "??"))
# if(divergent, label("divergent", " divergent"))

# change_id.short()
# if(divergent, label("divergent", "??"))


[colors]
# "empty" = "green"
# "working_copy empty" = "bright green"
# "working_copy email" = "yellow"
# "working_copy description" = "bright normal"

# TODO: I probably want to uncomment these after a bit
# Colors invisible in bright themes
# "working_copy description" = "bright white"
# "op-log head description" = "bright white"
# "op-log head tags" = "bright white"
# "diff file_header" = "bright white"
